
services:
  db:
    image: mysql:8.0
    container_name: ecommerce-db-gfs
    restart: always
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ecommerce-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: ecommerce-backend-image-gfs
    container_name: ecommerce-backend-gfs
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ecommerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    ports:
      - "8089:8089"
    networks:
      - ecommerce-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: ecommerce-frontend-image-gfs
    container_name: ecommerce-frontend-gfs
    restart: always
    ports:
      - "86:80"
    depends_on:
      - backend
    networks:
      - ecommerce-net

volumes:
  db_data:

networks:
  ecommerce-net:
    driver: bridge
